name: Build docker image

on:
  push:
    branches:
      - test/claasp-image-gh-creation

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # - name: Docker login
    #   env:
    #     DOCKER_USER: ${{ secrets.DOCKER_USER }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   run: |
    #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    # - name: Build Docker Image
    #   run: |
    #     docker build -t yessicard/docker-claasp-testing:latest ./docker/

    # - name: Push Docker Image
    #   run: |
    #     docker push yessicard/docker-claasp-testing:latest

    - name: Run pytests
      run: docker run --rm -v $PWD:/home/sage/tii-claasp claasp-lib make remote-pytest
