name: Build docker image

on:
  push:
    branches:
      - test/claasp-image-gh-creation

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: *
        restore-keys: *

    - name: Build
      uses: docker/build-push-action@v4
      id: built-image
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: false
        load: true
        tags: my-docker-image
        cache-from: type=local,src=/tmp/.buildx-cache,mode=max

    - name: Run pytest
      run: |
        docker run --rm my-docker-image pytest -v