name: Build docker image

on:
  push:
    branches:
      - test/claasp-image-gh-creation

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Inspect
      run: |
        docker image inspect my-docker-image:latest  

    - name: Run pytest
      run: |
        docker run --rm my-docker-image pytest -v
